#!/bin/bash
# Ragnawars Machine Installer - Maintained by Gidz Cross
# Semi Automated Installer for rAthena using Debian 10 Only
# Special Thanks to Magnificat
# General
DEV=0
INSTALLER_VERSION="v1.0"
STEPS=9
# Colors
BLUE='\033[0;36m'
GREEN='\033[0;92m'
YELLOW='\033[0;93m'
NC='\033[0m'

# Credentials
USERID=$(date +%s | sha256sum | base64 | head -c 3 ; echo)
USERPASS=$(date +%s | sha256sum | base64 | head -c 6 ; echo)
RATHENAPASS="gidzdlcrz"
RAGSQLPASS=$(date +%s | sha256sum | base64 | head -c 10 ; echo)

# URLs
URL_RA="https://rathena.org/board"
URL_RAGIT="https://github.com/rathena/rathena"
URL_FLUXGIT="https://github.com/rathena/FluxCP"
SERVER_IPLIST=$(ip addr|awk '/eth0/ && /inet/ {gsub(/\/[0-9][0-9]/,""); print $2}')
SERVER_IP=$(echo $SERVER_IPLIST | cut -d ' ' -f 1 )

if [ $DEV -eq 1 ]
then
	VERSION="${INSTALLER_VERSION} - ${YELLOW}Development Script${NC}"
else
	VERSION="${INSTALLER_VERSION}"
fi

echo "\033c"
echo "Welcome to ${BLUE}Ragnawars Machine${NC}, an unattended installer by Gidz Cross"
echo "Version: ${VERSION}\n"
echo "The script will now begin to install stuff on your system. Please be patient as this could take a while!\n"


echo "${BLUE}Step 1/${STEPS}:${NC} Updating your OS"
apt-get -qy update > /dev/null
apt-get -qy upgrade > /dev/null
echo ""
echo "Success!"
echo ""


echo "${BLUE}Step 2/${STEPS}:${NC} Installing Prerequisites"
apt-get -qy install expect wget sudo > /dev/null
echo ""
echo "Success!"
echo ""


echo "${BLUE}Step 3/${STEPS}:${NC} Installing MySQL Stuff"
apt-get -qy install libaio1 libdbd-mariadb-perl libdbi-perl libterm-readkey-perl libhtml-template-perl > /dev/null
export DEBIAN_FRONTEND=noninteractive 
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password password ragnarok"'
bash -c 'debconf-set-selections <<< "mariadb-server mariadb-server/root_password_again password ragnarok"'

apt-get -qy install mariadb-server
wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/msi.sh
chmod +x msi.sh
./msi.sh
rm msi.sh


echo ""
echo "${BLUE}Step 4/${STEPS}:${NC} Installing Apache2 & PHP"
echo " * Installing Apache2"
apt-get -qy install apache2 > /dev/null
echo " * Installing PHP"
apt-get -qy install libapache2-mod-php php-mysql php-gd php-mbstring php-xml > /dev/null
apt-get install php-curl
systemctl restart apache2
echo ""


echo "${BLUE}Step 5/${STEPS}:${NC} Installing rA specific packages"
echo " * Installing git, make, g++"
apt-get -qy install git make libmariadb-dev libmariadbclient-dev libmariadbclient-dev-compat > /dev/null
echo " * Installing Utilities"
apt-get -qy install zlib1g-dev libpcre3-dev nano zip unzip zenity gcc g++ > /dev/null
echo ""
echo "Success!"


echo "${BLUE}Step 6/${STEPS}:${NC} Creating MySQL Database"
mysqladmin -u root -pragnarok create ragnarok
mysqladmin -u root -pragnarok create logs
mysql -u root -pragnarok -e "CREATE USER ragnarok@localhost IDENTIFIED BY 'gidzdlcrz';"
mysql -u root -pragnarok -e "GRANT ALL PRIVILEGES ON ragnarok.* TO 'ragnarok'@'localhost';"
mysql -u root -pragnarok -e "GRANT ALL PRIVILEGES ON logs.* TO 'ragnarok'@'localhost';"
mysql -u root -pragnarok -e "FLUSH PRIVILEGES;"
echo ""
echo "Success!"
echo ""


echo "${BLUE}Step 7/${STEPS}:${NC} Installing phpMyAdmin"
wget -q https://files.phpmyadmin.net/phpMyAdmin/4.7.3/phpMyAdmin-4.7.3-english.zip
unzip -qq phpMyAdmin-4.7.3-english.zip
rm phpMyAdmin-4.7.3-english.zip
mv phpMyAdmin-4.7.3-english phpmyadmin
cd phpmyadmin
mv config.sample.inc.php config.inc.php
echo "<?php" > /var/www/html/phpmyadmin/config.inc.php
BLOWFISH=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
echo "\$cfg['blowfish_secret'] = '${BLOWFISH}';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i=0;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$i++;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['host'] = 'localhost';" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowRoot'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['AllowNoPassword'] = false;" >> /var/www/html/phpmyadmin/config.inc.php
echo "\$cfg['Servers'][\$i]['auth_type']     = 'cookie';" >> /var/www/html/phpmyadmin/config.inc.php
chown -R www-data:www-data /var/www/html
chmod 0660 /var/www/html/phpmyadmin/config.inc.php
echo ""
echo "Success!"
echo ""


cd /var/www/html/data/schemas/logindb/
wget -q https://raw.githubusercontent.com/gamingmagic/unattended-installer/master/cp_cmspages.20170808161901.sql
chown -R www-data:www-data /var/www/html
cd /home/


echo "${BLUE}Step 8/${STEPS}:${NC} Finishing up!"
echo ""
echo ""
echo ""
echo "${YELLOW}**************************ALL DONE!!!*************************${NC}"
echo "${BLUE}Thank you for using Ragnawars Machine!${NC}"
echo ""
echo ""
echo "${GREEN} -- System Stuff${NC}"
echo "Linux User 'rathena' Password: ${RATHENAPASS}"
echo "Server IP: ${SERVER_IP}"
echo ""
echo ""
echo "${GREEN} -- MySQL Stuff${NC}"
echo "MySQL user: ragnarok"
echo "MySQL password: gidzdlcrz"
echo "phpMyAdmin: http://${SERVER_IP}/phpmyadmin"
echo ""
echo ""
exit 0
